### ISSUE TITLE
LKRG Debian package - systemd unit does not automatically start - lkrg.service is a disabled or a static unit, not starting it.

### ISSUE THREAD

**Issue by adrelanos** [openwall/lkrg#108]
> sudo apt install lkrg
```
...
Setting up lkrg (0.9.1-3) ...
Setting up lkrg-systemd (0.9.1-3) ...
lkrg.service is a disabled or a static unit, not starting it.
```

It requires a manual `sudo systemctl enable lkrg` and reboot or `sudo systemctl start lkrg`.

I am wondering, why does it do that?

The Debian default is to enable systemd units after installation.

**Comment by adrelanos** [comment]
https://github.com/Whonix/lkrg/blob/old-master/debian/lkrg-dkms.service did not have this issue.

Some change in https://github.com/openwall/lkrg/blob/main/scripts/bootup/systemd/lkrg.service might be causing this issue.

old:
`WantedBy=multi-user.target`

new:
`WantedBy=sysinit.target`

Wondering if this is causing it.

* [When should a systemd unit file use sysinit.target vs multi-user.target?](https://unix.stackexchange.com/questions/556923/when-should-a-systemd-unit-file-use-sysinit-target-vs-multi-user-target)
* https://www.freedesktop.org/software/systemd/man/bootup.html

In my understanding, `WantedBy=multi-user.target` does not invalidate `Before=sysinit.target`.

**Comment by adrelanos** [comment]
Even replacing the systemd unit https://github.com/Whonix/lkrg/blob/old-master/debian/lkrg-dkms.service does not fix this. So I guess it must be something else in the Debian packaging.

**Comment by adrelanos** [comment]
For debugging maybe [`debian/lkrg-systemd.postinst`](https://github.com/Whonix/lkrg/blob/debian-packaging-systemd-debugging/debian/lkrg-systemd.postinst) can help.

(Not suggested for merge. Only manual use for debugging.)

This is the debug output:

```
sudo dpkg -i lkrg-systemd_0.9.1-3_all.deb 
```

```
(Reading database ... 328917 files and directories currently installed.)
Preparing to unpack .../lkrg-systemd_0.9.1-3_all.deb ...
Unpacking lkrg-systemd (0.9.1-3) over (0.9.1-3) ...
Setting up lkrg-systemd (0.9.1-3) ...
+ set -e
+ true '
#####################################################################
## INFO: BEGIN: lkrg-systemd postinst configure' '0.9.1-3
#####################################################################
'
+ export _DEB_SYSTEMD_HELPER_DEBUG=1
+ _DEB_SYSTEMD_HELPER_DEBUG=1
+ true 'INFO: debhelper beginning here.'
+ '[' configure = configure ']'
+ deb-systemd-helper debian-installed lkrg.service
(deb-systemd-helper DEBUG) is purge = no
(deb-systemd-helper DEBUG) action = debian-installed, scriptname = lkrg.service, service_path = /lib/systemd/system/lkrg.service
+ deb-systemd-helper unmask lkrg.service
(deb-systemd-helper DEBUG) is purge = no
(deb-systemd-helper DEBUG) action = unmask, scriptname = lkrg.service, service_path = /lib/systemd/system/lkrg.service
(deb-systemd-helper DEBUG) rmdir_if_empty /var/lib/systemd/deb-systemd-helper-masked
(deb-systemd-helper DEBUG) rmdir(/var/lib/systemd/deb-systemd-helper-masked) failed (Directory not empty)
+ deb-systemd-helper --quiet was-enabled lkrg.service
(deb-systemd-helper DEBUG) is purge = no
(deb-systemd-helper DEBUG) action = was-enabled, scriptname = lkrg.service, service_path = /lib/systemd/system/lkrg.service
(deb-systemd-helper DEBUG) Reading state file /var/lib/systemd/deb-systemd-helper-enabled/lkrg.service.dsh-also
(deb-systemd-helper DEBUG) Contents: $VAR1 = [
          '/etc/systemd/system/multi-user.target.wants/lkrg.service'
        ];

(deb-systemd-helper DEBUG) Link /etc/systemd/system/multi-user.target.wants/lkrg.service is missing, considering lkrg.service was-disabled.
+ deb-systemd-helper update-state lkrg.service
(deb-systemd-helper DEBUG) is purge = no
(deb-systemd-helper DEBUG) action = update-state, scriptname = lkrg.service, service_path = /lib/systemd/system/lkrg.service
(deb-systemd-helper DEBUG) Reading state file /var/lib/systemd/deb-systemd-helper-enabled/lkrg.service.dsh-also
(deb-systemd-helper DEBUG) Old state file contents: $VAR1 = [
          '/etc/systemd/system/multi-user.target.wants/lkrg.service'
        ];

(deb-systemd-helper DEBUG) Renaming temp file /var/lib/systemd/deb-systemd-helper-enabled/.stateWZIbk.tmp to state file /var/lib/systemd/deb-systemd-helper-enabled/lkrg.service.dsh-also
(deb-systemd-helper DEBUG) Reading state file /var/lib/systemd/deb-systemd-helper-enabled/lkrg.service.dsh-also
(deb-systemd-helper DEBUG) New state file contents: $VAR1 = [
          '/etc/systemd/system/sysinit.target.wants/lkrg.service'
        ];

+ '[' configure = configure ']'
+ '[' -d /run/systemd/system ']'
+ systemctl --system daemon-reload
+ '[' -n 0.9.1-3 ']'
+ _dh_action=restart
+ deb-systemd-invoke restart lkrg.service
lkrg.service is a disabled or a static unit not running, not starting it.
+ true 'INFO: Done with debhelper.'
+ true '
#####################################################################
## INFO: END  : lkrg-systemd postinst configure' '0.9.1-3
#####################################################################
'
+ exit 0
```

Related scripts by Debian responsible for that:

* `/usr/bin/deb-systemd-helper`
* `/usr/bin/deb-systemd-invoke`

**Comment by morfikov** [comment]
> > sudo apt install lkrg
> 
> ```
> ...
> Setting up lkrg (0.9.1-3) ...
> Setting up lkrg-systemd (0.9.1-3) ...
> lkrg.service is a disabled or a static unit, not starting it.
> ```
> 
> It requires a manual `sudo systemctl enable lkrg` and reboot or `sudo systemctl start lkrg`.
> 
> I am wondering, why does it do that?
> 
> The Debian default is to enable systemd units after installation.

Basically I turned it off in the `debian/rules` file because I don't really see the purpose of having the systemd service in first place. Many users, including me, when we want to load a module in the case of systemd init system, we use the native systemd services, which use the config files located in the `/etc/sysctl.d/` , `/etc/modules-load.d/` and `/etc/modprobe.d/` dirs. So basically it was the best approach to support multiple init systems, which also use the dirs when loading and configuring kernel modules. I would remove the service altogether in the deb package, but some users wanted it, so I left it in its place, but in the disabled state and let the systemd native service to take care of loading and configuring the lkrg kernel module when system is booted.

**Comment by adrelanos** [comment]
Ah. Thanks for the tip. Finally found it in `debian/rules`:

```
override_dh_installsystemd:
        dh_installsystemd --no-enable --no-stop-on-upgrade
```

Well, there's a separate package `lkrg-systemd`. A user would reasonably expect if such a package gets installed that the systemd unit gets enabled after installation plus on top that this is the Debian way of doing it.

So since the systemd unit is split into a separate package a great compromise would be to enable the systemd unit after installation of the `lkrg-systemd` package.

> Basically I turned it off in the `debian/rules` file because I don't really see the purpose of having the systemd service in first place.

Right. Having a systemd unit is debatable for a kernel module. I don't see much point then in a systemd service too if it can be made without.

Except a useful feature of a systemd unit file is the usability feature: kernel boot parameter `nolkrg` for recovery purposes. But perhaps that could instead be implemented inside the LKRG kernel module?

> Many users, including me, when we want to load a module in the case of systemd init system, we use the native systemd services, which use the config files located in the `/etc/sysctl.d/` , `/etc/modules-load.d/` and `/etc/modprobe.d/` dirs.

Sure, if that works... What I would like to see is a user experience:

`sudo apt install lkrg` -> all set. Done. No further user action required. Optional configuration possible. That is the Debian way.

**Comment by morfikov** [comment]
> Well, there's a separate package lkrg-systemd. A user would reasonably expect if such a package gets installed that the systemd unit gets enabled after installation plus on top that this is the Debian way of doing it.

In the case of a normal services, yes, but it's not a normal service. According to some paper I've read, they mention that when some exploit is already loaded, and after it you load lkrg, then in such situation lkrg is less likely to detect the exploit or even can't do it. That's why you should load the module as soon as possible. So this is the first thing. The second one is, that the current config will break, since you have files in /etc/sysctl.d/ , /etc/modules-load.d/ and /etc/modprobe.d/ . So the service simply don't make any sense. Also, systemd service only would apply to systemd installations, whereas the files in /etc/sysctl.d/ , /etc/modules-load.d/ and /etc/modprobe.d/ dirs applies to sysvinit, openrc and systemd. That's why the service is in separate package, and its purpose is just to satisfy people who want to have it and don't want to use the config files in the aforementioned dirs.

> Except a useful feature of a systemd unit file is the usability feature: kernel boot parameter nolkrg for recovery purposes. But perhaps that could instead be implemented inside the LKRG kernel module?

If I knew that lkrg is a problem, I would use a different kernel cmd parameter: `systemd.unit=emergency.target` -- which drops me to the shell before even mounting (as read/write) the root file system, and I can disable whatever service I want. So this `nolkrg` parameter doesn't really make sense to me. :)

> 
sudo apt install lkrg -> all set. Done. No further user action required. Optional configuration possible. That is the Debian way.

And that's what it does now. Of course you need to reboot. :)

**Comment by Adam-pi3** [comment]
Hm... I believe I'm not competent enough in the field to make any decisions. @adrelanos and @morfikov what is the common ground in that field? What do you suggest to do?
@solardiz What do you think?

**Comment by morfikov** [comment]
My opinion is presented above -- I would just remove the service altogether and rely on the other mechanisms which could load the module in boot phase as soon as possible. No extra service that supports only one init is required.

**Comment by adrelanos** [comment]
> My opinion is presented above -- I would just remove the service altogether and rely on the other mechanisms which could load the module in boot phase as soon as possible. No extra service that supports only one init system is required.

Agreed. Remove the lkrg systemd unit file. And then remove the lkrg-systemd package.

Reasons:

* Kernel modules in Debian don't ship systemd units.
* Debian doesn't ship packagename-systemd packages. Also other 1 file packages are avoided to keep repository overhead low.

**Comment by adrelanos** [comment]
Would you like to remove the systemd unit from the Debian package @morfikov or should I send a pull request?

**Comment by morfikov** [comment]
I was for removing it since the very beginning, but some people wanted it to stay. You can send a pull request if you want.

**Comment by adrelanos** [comment]
Would be useful to merge https://github.com/openwall/lkrg/pull/114 first. That will make things less confusing.

Because a full removal of lkrg-systemd package has a slight chance of getting reverted. But if that happens, at least the `Recommends:` is gone.

I'll add another pull request for full removal of lkrg-systemd package.

**Comment by solardiz** [comment]
> It requires a manual `sudo systemctl enable lkrg` and reboot or `sudo systemctl start lkrg`.
> 
> I am wondering, why does it do that?

Outside of Debian package specifics, we had also decided on not enabling the systemd service by default in https://github.com/openwall/lkrg/issues/74#issuecomment-826306287 (see that issue/comment for the rationale) and implemented that in 3c2b7b2e20b2891a86eba35c6fd8a76461c1b505.

That rationale primarily applied to manual build/installation of LKRG, but to some extent it also does to distro packages. Things are trickier with those, though, as especially with DKMS it is indeed possible to get an unbootable system if the kernel upgrades to a version where the installed version of LKRG fails, yet LKRG was already successfully tested with a previous kernel and thus is enabled on bootup. The `nolkrg` option would then be the way out.

If we start using `/etc/modules-load.d`, then we'd effectively be enabling LKRG on bootup by default, thus reintroducing the problem/criticism mentioned in #74.

There's no perfect solution here, it seems.

**Comment by sempervictus** [comment]
I think that having init scripts for whatever init system folks use is handy - its a system-native mechanism to load the modules, for systemd-based stuff this is not an uncommon semantic either, and the openrc/legacy people can always write their own if so desired and PR them to the repository.
Having options is never a bad thing, and the maintenance burden is minimal if that in this case, so i vote against removing good code for aesthetic concerns.

**Comment by solardiz** [comment]
At this point, I don't know what this issue is for. I think we may as well close it with no action. The title "LKRG Debian package - systemd unit does not automatically start - lkrg.service is a disabled or a static unit, not starting it." merely describes what we have, and there's not necessarily any issue with that.

If @adrelanos and @morfikov feel about enabling the service in the Debian package by default, I assume one of them can create a pull request with `systemctl enable lkrg` or even also with `systemctl start lkrg` on Debian package installation - do this in the Debian package only, please, as the current way of not enabling/starting LKRG by default is for a reason and is documented.
