### ISSUE TITLE
Update UMH documentation to reflect new enforcement behavior

### ISSUE THREAD

**Issue by solardiz** [openwall/lkrg#26]
#23 changed the mild enforcement behavior for UMH from blocking execution to killing the process. We probably need to update the documentation and LKRG's messages and source code comments accordingly.

We currently have this in `README`:

```
- lkrg.umh_enforce (1)
  How to act on UMH usage violations.  Allowed values are 0 (log only), 1
  (prevent execution), and 2 (panic the kernel).
```

And these in code:

```
./src/p_lkrg_main.c:MODULE_PARM_DESC(umh_enforce, "umh_enforce [1 (prevent execution) is default]");
./src/modules/comm_channel/p_comm_channel.c:      "PREVENT EXECUTION",
./src/modules/comm_channel/p_comm_channel.c:                  P_CTRL(p_umh_enforce) = 0x1;   // Prevent execution
./src/modules/comm_channel/p_comm_channel.c:                  P_CTRL(p_umh_enforce) = 0x1;   // Prevent execution
./src/modules/exploit_detection/syscalls/p_call_usermodehelper/p_call_usermodehelper.c:            /* Prevent execution */
```

I think we should now use the same wording that we do for `pint_enforce=1` ("kill the task", "KILL TASK", and "Kill task").

@Adam-pi3 Do you agree?

@oshogbo Can you please take care of these? Thanks!

**Comment by oshogbo** [comment]
Yes I can change that

**Comment by oshogbo** [comment]
You can assign this issue to me.

**Comment by oshogbo** [comment]
@Adam-pi3 ping?

**Comment by Adam-pi3** [comment]
I've been running a few more tests - sorry for delay. I'm not sure that "kill [the] task" is a valid description for that specific feature. The main reason why I'm not 100% sure is that we do not kill the task which generate an UMH. We do kill the task from UMH WQ pool-threads which are created for handling the request. We do not kill the "attacking process". More-over, the attacking process is not aware what's going on. It can only observe the side effect of running UMH. In such case, because we kill UMH WQ thread (not the attacking process), UMH fails to run. The same side-effect "attacking process" sees with old logic.
If we want to be more accurate we can say "Prevent execution by killing UMH WQ  task" but it's too long.
@solardiz what's your take away from such details? If you are fine with "Kill [the] task" I'm OK as well. I just wanted to point out that this is different "killing" comparing to other places where we describe it.

**Comment by solardiz** [comment]
Thanks @Adam-pi3. Given your explanation, I think we should keep the old description. I'm closing this issue.
