### ISSUE TITLE
LKRG fails to initialize with a certain combination of boot parameters

### ISSUE THREAD

**Issue by savchenko** [openwall/lkrg#27]
Debian Buster, stock kernel: `4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18)`

UEFI secure boot is enabled. Grub cmdline, newlines added for readability:
```
quiet kaslr apparmor=1 security=apparmor ipv6.disable=1 kernel.kptr_restrict=2 kernel.kexec_load_disabled=1
slab_nomerge slub_debug=FZP mce=0 page_poison=1 mitigations=auto,nosmt audit=0 efi=disable_early_pci_dma
init_on_alloc=1 init_on_free=1 pti=on module.sig_enforce=1 vsyscall=none extra_latent_entropy intel_iommu=on
fsck.mode=force fsck.repair=preen
```

relevant dmesg output:
```
kern  :warn  : [  +0.009410] p_lkrg: loading out-of-tree module taints kernel.
kern  :crit  : [  +0.051397] [p_lkrg] Loading LKRG...
kern  :err   : [  +0.000003] [p_lkrg] System does NOT support SMAP. LKRG can't enforce SMAP validation :(
kern  :info  : [  +0.002052] Freezing user space processes ... (elapsed 0.077 seconds) done.
kern  :info  : [  +0.077095] OOM killer disabled.
kern  :warn  : [  +0.001255] [p_lkrg] 6/23 UMH paths are allowed...
kern  :notice: [  +0.047055] Lockdown: Use of kprobes is restricted; see https://wiki.debian.org/SecureBoot
kern  :err   : [  +0.000004] [p_lkrg] [kretprobe] register_kretprobe() for <__x64_sys_execve> failed! [err=-1]
kern  :err   : [  +0.000412] [p_lkrg] ERROR: Can't hook sys_execve :(
kern  :crit  : [  +0.015075] [p_lkrg] Can't initialize exploit detection features! Exiting...
kern  :info  : [  +0.044015] OOM killer enabled.
kern  :info  : [  +0.000003] Restarting tasks ... done.
```

Is this due to the "lockdown" activated by the presence of Secure Boot? If yes, could you suggest any workarounds?

Thank you.

**Comment by solardiz** [comment]
I think this belongs on lkrg-users rather than on GitHub since it's not an LKRG bug: we clearly document that LKRG requires kprobes, and the above clearly shows that you have them disallowed. Discussing your local configuration details and workarounds is more of an lkrg-users matter. That said:

We exchanged a few private e-mails with @mjg59 earlier this year, where he shared this (and I hope he doesn't mind me posting it publicly):

```
The upstream implementation only restricts kprobes when lockdown is in
"confidentiality" mode, which is not the default when secure boot is
used. This problem will go away once everyone is rebased on the
upstream implementation.
```

So either you have lockdown in "confidentiality" mode, which is not the default, or you're on an unfortunate kernel revision that already got the restriction but hasn't yet been rebased on the upstream implementation.

Further in that e-mail thread, we touched on whether restricting kprobes makes sense in "confidentiality" mode, and Matthew suggested "it's perfectly reasonable to question whether it serves the goals of the patchset." So I suppose we could bring this up on LKML and hopefully get that part of lockdown also dropped from upstream, but we didn't bother yet. You may. Whoever does this would need to read up on lockdown's threat models (which look questionable to me, but I might be missing something) and rationale behind that patchset first.

**Comment by savchenko** [comment]
> Discussing your local configuration details and workarounds is more of an lkrg-users matter. 

Noted. I should probably try with the newer kernel available in testing/Sid to check if either:
- Lockdown can be reduced to "integrity" level.
- It is possible to enable kprobes in "confidentiality" mode.

> So either you have lockdown in "confidentiality" mode, which is not the default, or you're on an unfortunate kernel revision that already got the restriction but hasn't yet been rebased on the upstream implementation.

Probably the latter as this is bog-standard Debian kernel and I am not changing lockdown settings.
Passing `lockdown=integrity` to 4.19 makes no difference as it is not aware about such parameter yet.

I have tried compiling LKRG with the 5.8.X kernel from backports, however this has failed as `cryptohash.h` is available only in [packages for 4.19.X kernel series](https://packages.debian.org/search?mode=exactfilename&suite=buster&section=all&arch=any&searchon=contents&keywords=cryptohash.h):
```
make[1]: Entering directory '/usr/src/linux-headers-5.8.0-0.bpo.2-amd64'
  CC [M]  /root/lkrg-0.8.1/src/modules/ksyms/p_resolve_ksym.o
In file included from /root/lkrg-0.8.1/src/modules/ksyms/p_resolve_ksym.c:19:
/root/lkrg-0.8.1/src/modules/ksyms/../../p_lkrg_main.h:63:10: fatal error: linux/cryptohash.h: No such file or directory
 #include <linux/cryptohash.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

> So I suppose we could bring this up on LKML and hopefully get that part of lockdown also dropped from upstream, but we didn't bother yet. You may. Whoever does this would need to read up on lockdown's threat models (which look questionable to me, but I might be missing something) and rationale behind that patchset first.

Rationale behind the lockdown is explained in [Matthew's writeup](https://mjg59.dreamwidth.org/55105.html).

There are quite a few complains about kprobes / bpf all around the web and looking at [LKML](https://lkml.org/lkml/2019/3/6/800), it seems like kprobes restrictions were introduced by David Howells. Might worth starting a conversation via dhowells@redhat.com unless there are better ways to reach him.

**Comment by savchenko** [comment]
Attempted the same on Debian Sid, v5.9.0 kernel:
```
# make -j2
make -C /lib/modules/5.9.0-2-amd64/build M=/root/lkrg-0.8.1 modules
make[1]: Entering directory '/usr/src/linux-headers-5.9.0-2-amd64'
  CC [M]  /root/lkrg-0.8.1/src/modules/ksyms/p_resolve_ksym.o
  CC [M]  /root/lkrg-0.8.1/src/modules/hashing/p_lkrg_fast_hash.o
In file included from /root/lkrg-0.8.1/src/modules/hashing/p_lkrg_fast_hash.c:22:
/root/lkrg-0.8.1/src/modules/hashing/../../p_lkrg_main.h:63:10: fatal error: linux/cryptohash.h: No such file or directory
   63 | #include <linux/cryptohash.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
I thought that missing `cryptohash.h` is a Debian-specific issue, however trying to compile LKRG on a fresh Ubuntu 20.10 VM resulted in exactly the same error, albeit a different `apt-file` search result.

Ubuntu 20.10, note the mismatch between headers and kernel versions:
```
$ dpkg -S cryptohash.h
dpkg-query: no path found matching pattern *cryptohash.h*
$ apt-file search cryptohash.h
libghc-cryptohash-doc: /usr/lib/ghc-doc/haddock/cryptohash-0.11.9/cryptohash.haddock
linux-5.7-headers-5.7.0-15: /usr/src/linux-5.7-headers-5.7.0-15/include/linux/cryptohash.h
$ uname -r
5.8.0-29-generic
```

Sid:
```
$ dpkg -S cryptohash.h
dpkg-query: no path found matching pattern *cryptohash.h*
$ apt-file search cryptohash.h
libghc-cryptohash-doc: /usr/lib/ghc-doc/haddock/cryptohash-0.11.9/cryptohash.haddock
```
Buster (stable):
```
$ dpkg -S cryptohash.h
linux-headers-4.19.0-12-common: /usr/src/linux-headers-4.19.0-12-common/include/linux/cryptohash.h
$ apt-file search cryptohash.h
libghc-cryptohash-doc: /usr/lib/ghc-doc/haddock/cryptohash-0.11.9/cryptohash.haddock
linux-headers-4.19.0-10-common: /usr/src/linux-headers-4.19.0-10-common/include/linux/cryptohash.h
linux-headers-4.19.0-10-common-rt: /usr/src/linux-headers-4.19.0-10-common-rt/include/linux/cryptohash.h
linux-headers-4.19.0-11-common: /usr/src/linux-headers-4.19.0-11-common/include/linux/cryptohash.h
linux-headers-4.19.0-11-common-rt: /usr/src/linux-headers-4.19.0-11-common-rt/include/linux/cryptohash.h
```

**Comment by solardiz** [comment]
Regarding the `cryptohash.h` issue, you seem to be using an out of date revision of LKRG. For GitHub issues, we assume that you use the latest LKRG from this repo, not any past release, nor any distro package.

**Comment by solardiz** [comment]
> I should probably try with the newer kernel available in testing/Sid

Probably yes.

> to check if either:
> 
>     * Lockdown can be reduced to "integrity" level.
> 
>     * It is possible to enable kprobes in "confidentiality" mode.

That's not my understanding of what Matthew wrote in those e-mails. My understanding is that there was a non-upstream implementation of lockdown in some distro kernels, which restricted kprobes even in "integrity" mode. So you'd hope to no longer be at an implementation like that when you upgrade to a newer kernel.

**Comment by savchenko** [comment]
> Regarding the `cryptohash.h` issue, you seem to be using an out of date revision of LKRG. For GitHub issues, we assume that you use the latest LKRG from this repo, not any past release, nor any distro package.

I was using https://www.openwall.com/lkrg/lkrg-0.8.1.tar.gz which is mentioned in Readme and at the official website. Will re-run tests with master branch and report back.

**Comment by solardiz** [comment]
It is well-known to us (and has been discussed on lkrg-users) that LKRG 0.8.1 doesn't build on Linux 5.8+. The README here hasn't been updated from that release - maybe we should be updating it with such knowledge - but then it also says the release was only tested until Linux 5.7 inclusive.

For Linux 5.8+, you really absolutely have to use our latest code. We currently recommend that on older kernels as well.

**Comment by solardiz** [comment]
I think we don't need to track this discussion as a GitHub issue, so I'm closing it.

**Comment by madaidan** [comment]
What exactly does LKRG require kprobes for? Are they an absolute requirement? The documentation only states that these are required for the protected user space processes feature but it also states that this functionality is only present in the experimental branch (which also appears to have been dropped?). Could kprobe usage perhaps be replaced with some other mechanism or, at the very least, could a compilation option to disable the code requiring it be added?

The reasoning behind this is that hardened kernels often have kprobes disabled to reduce attack surface (Whonix's hardened-kernel, CLIP OS' kernel config, Alexander Popov's kconfig-hardening-check, grsecurity, etc.) so they are not ideal.

**Comment by solardiz** [comment]
Again, this is more of a topic for lkrg-users, but I don't mind replying in here:

> What exactly does LKRG require kprobes for?

For all of its kernel function hooking, which it does for almost all of its features. Lately, LKRG's use of kprobes tend to be optimized to ftrace, though (and this is why LKRG works on 5.8 and 5.9 at all, see http://blog.pi3.com.pl/?p=831).

> Are they an absolute requirement?

Currently, yes.

> The documentation only states that these are required for the protected user space processes feature

Where does it state that?

> but it also states that this functionality is only present in the experimental branch (which also appears to have been dropped?).

Right, I thought the mentions of this functionality were dropped as well. Maybe you're referring to the wiki? The wiki is unfortunately way out of date, and doesn't reflect LKRG's current focus. Maybe we need to drop the wiki content entirely, replacing it with a mere note that people should refer to current LKRG documentation files instead.

> Could kprobe usage perhaps be replaced with some other mechanism

Yes. We're considering using ftrace explicitly, but it won't solve the problem you mention below. Another alternative is going for a lower-level and more hackish and arch-specific method such as @milabs' khook: https://github.com/milabs/khook

> or, at the very least, could a compilation option to disable the code requiring it be added?

No. That would be equivalent to disabling LKRG.

> The reasoning behind this is that hardened kernels often have kprobes disabled to reduce attack surface (Whonix's hardened-kernel, CLIP OS' kernel config, Alexander Popov's kconfig-hardening-check, grsecurity, etc.) so they are not ideal.

I don't recall @adrelanos who integrated LKRG into Whonix complaining about that. Maybe he changed that config to accommodate LKRG?

As to @a13xp0p0v's https://github.com/a13xp0p0v/kconfig-hardened-check, it lists both kprobes and ftrace as disabled for attack surface reduction. I think normally neither adds to attack surface available to non-root, but I understand that under some threat models even APIs available from the same privilege level (root, ring 0) are colloquially called part of "attack surface". What LKRG does is in fact technically rootkit-like behavior - with the huge difference that it's authorized by the sysadmin and mitigates attacks, contrary to what a rootkit would be/do. If we move away from using these official function hooking APIs in favor of e.g. khook, we'll be technically even more rootkit-like. We'll bypass the anti-hooking hardening like those kernel configs you mention, but if there's ever another kernel integrity solution loaded onto the same system with LKRG then we'll look even more suspicious to that than we look now.

**Comment by madaidan** [comment]
Thanks for the reply. It cleared up a lot of things.

> Maybe you're referring to the wiki?

I was referring to that, sorry.

> Maybe he changed that config to accommodate LKRG?

hardened-kernel still disables kprobes.

https://github.com/Whonix/hardened-kernel/blob/ba34167459fab24b973f722b438bd09b83593ae6/usr/share/hardened-kernel/hardened-vm-kernel#L685

ftrace is also disabled.

https://github.com/Whonix/hardened-kernel/blob/ba34167459fab24b973f722b438bd09b83593ae6/usr/share/hardened-kernel/hardened-vm-kernel#L4746

So it seems like there is no good solution to this then. It's either additional ftrace/kprobes attack surface (our threat model involves attackers with root) or no LKRG. I'm not sure what to do. I will have to think about this.

**Comment by solardiz** [comment]
> our threat model involves attackers with root

Threat model that involve attackers with root yet try to harden the kernel from them are weird. Sure there is BSD securelevel and there were e.g. LKRG "protected features" in its "experimental branch" (now dropped), but these are extremely hard to use reasonably. I don't know what exactly your threat model is and whether it's possibly reasonable, but I think most are not.

**Comment by madaidan** [comment]
In Whonix, we are planning on shipping a full system AppArmor policy to enforce fine-grained restrictions upon every process, including those created by root in an attempt to minimize attack surface as much as humanly possible whilst also using a hardened kernel and placing all apps within a strict sandbox. Our goal is similar to that of AOSP's security model but on desktop Linux.

**Comment by solardiz** [comment]
What you describe makes sense, except that you seem to use the term "attack surface" to mean something that I think it normally does not, e.g. `ManadhataKaynarWing07.pdf` "A Formal Model for a System’s Attack Surface":

```
3.7 Attack Surface Definition
A system's attack surface is the subset of the system's
resources that an attacker can use to attack the system. An
attacker can use a system's entry points and exit points,
channels, and untrusted data items to either send (receive)
data into (from) the system to attack the system. Hence
the set of entry points and exit points, the set of channels,
and the set of untrusted data items are the relevant subset
of resources that are part of the attack surface.
```

Note that restricting what a process can do, while likely beneficial for system security, does not affect its attack surface. A more relevant term would be "least privilege principle", and some others, but not "attack surface".

**Comment by solardiz** [comment]
More relevant to our previous discussion on LKRG, what you describe doesn't imply distrusting root nor hardening the system from what root can do - rather, it's distrusting code quality of specific programs trusted not to be deliberately malicious. This is fine, and does not require hardening the kernel from deliberate attacks by root. What you do is restrict what those programs can do so they're less likely to shoot themselves or others in the foot, including when acting as confused deputies under a security attack via their input channels.

**Comment by madaidan** [comment]
> Note that restricting what a process can do, while likely beneficial for system security, does not affect its attack surface. A more relevant term would be "least privilege principle", and some others, but not "attack surface".

I was referring to the attack surface of the rest of the system. By restricting X program to its bare essentials, there is not much it could do to compromise Y (other parts of the system) as Y's attack surface from the perspective of X is mostly eliminated. I was not referring to the attack surface of X. Although, principle of least privilege would be a much better term indeed.

> More relevant to our previous discussion on LKRG, what you describe doesn't imply distrusting root nor hardening the system from what root can do - rather, it's distrusting code quality of specific programs trusted not to be deliberately malicious. This is fine, and does not require hardening the kernel from deliberate attacks by root. What you do is restrict what those programs can do so they're less likely to shoot themselves or others in the foot, including when acting as confused deputies under a security attack via their input channels.

If we only distrust specific programs then they could potentially attack "trusted" programs to bypass their restrictions whereas we aim to distrust the entire system so even e.g. a vulnerability in the init system won't be able to escalate to kernel mode. This can be particularly useful to prevent VM escapes — it is now significantly harder for an attacker to gain the privileges required for escaping the VM, even if they control some of the most "privileged" user space processes. This presentation describes something similar to what we're trying to achieve: https://www.blackhat.com/docs/us-17/thursday/us-17-Kralevich-Honey-I-Shrunk-The-Attack-Surface-Adventures-In-Android-Security-Hardening.pdf

**Comment by adrelanos** [comment]
We intent to implement [Multiple Boot Modes for Better Security - an Implementation of Untrusted Root](https://www.whonix.org/wiki/Dev/boot_modes). In essence, in grub boot menu user can choose to boot into user, secureadmin or superadmin. Secureadmin will be a untrusted root, confined by [apparmor-profile-everything](https://www.whonix.org/wiki/apparmor-profile-everything). The idea of an untrusted root is relatively new. It used to be considered "root = kernel". I don't know many sources that explain "untrusted root". There might be quite some explaining of the concept left to do. Best references for now coming to mind:

* https://lwn.net/Articles/523367/
* https://forums.whonix.org/t/untrusted-root-improve-security-by-restricting-root/7998

Another overview of all of our planned security enhancements, [Fixing the Desktop Linux Security Model](https://forums.whonix.org/t/fixing-the-desktop-linux-security-model/9172).

The idea behind [hardened-kernel](https://www.whonix.org/wiki/Hardened-kernel) and often generally is to avoid as many reasonably avoidable code paths as possible because these might have unknown vulnerabilities. For example, a few years ago Whonix was installing Pidgin by default but disabled most other protocols and extensions other than jabber.

The kernel is trusted (not because we want to, but we have to). One of the most privileged code we have control over. However, there is a massive amount of code and features in Linux. Trying to pick a good example. Not trying to pick on anything specific. For example, hardened-kernel disables Universal Disk Format (UDF). Do we really need that by default? Probably not. Therefore disabled. The idea is an attacker might have found a vulnerability in that code or some module which would be auto loaded. The then by exploiting that vulnerability get access to kernel space. This might then allow for more opportunities to attack the virtualizer or hardware.

There was a virtual machine escape vulnerability in VirtualBox floppy drive. By not enabling this functionality by default (we haven't heard from any users who where missing it), an attacker cannot exploit.

We used to call that "attack surface reduction" or "hardening". Perhaps not the best terminology?

Now the idea of harderned-kernel disabling kprobes and ftrace is also attack surface reduction.

Our main question now is:

**Do we gain more security by disabling kprobes and ftrace in hardened-kernel through attack surface reduction or more by using LKRG (which at the moment mandatoryly requires kprobes)?**

I guess a related question is, would untrusted root have a chance to make use of any code paths using kprobes / ftrace? (Similar to asking "could apparmor confined Firefox exploit a hypothetical vulnerability in SUID binary /bin/su?" The answer would be "no" (as long as apparmor works as expected).)

@solardiz 

> I don't recall @adrelanos who integrated LKRG into Whonix complaining about that. Maybe he changed that config to accommodate LKRG?

LKRG came first. I've not tried LKRG in combination with hardened-kernel yet.

While LKRG might soon be installed by default in Whonix, the [project status of hardened-kernel](https://www.whonix.org/wiki/Hardened-kernel#Project_Status) is different.

> Again, this is more of a topic for lkrg-users, but I don't mind replying in here:

Thank you very much for this! I think there is a certain "boundary" nowadays for many people to sign up on mailing lists. All your communications are very much appreciated!

**Comment by solardiz** [comment]
> > Maybe you're referring to the wiki?
> 
> I was referring to that, sorry

Not your fault. It was a bad idea for us to keep such outdated content around. I've just dropped most of the wiki content.

@adrelanos You might want to update the Whonix wiki accordingly, dropping any remaining links to LKRG wiki and maybe even quotes of content that is now considered obsolete. Thanks! (I didn't check what of this kind you might still have in there, but I recall that you had some of this before.)

Of course, since these are wikis, if anyone wants to explore the history, they can.

**Comment by solardiz** [comment]
@adrelanos @madaidan I might comment on what you wrote later, but JFYI there was this thread on oss-security recently:

https://www.openwall.com/lists/oss-security/2020/10/05/5
https://www.openwall.com/lists/oss-security/2020/10/06/11
https://www.openwall.com/lists/oss-security/2020/10/19/1
https://www.openwall.com/lists/oss-security/2020/10/19/4

I guess most of what's talked about there is already known to you, but maybe some thoughts are new, or are useful reminders.

**Comment by savchenko** [comment]
> For Linux 5.8+, you really absolutely have to use our latest code. We currently recommend that on older kernels as well.

For what it worth, https://github.com/openwall/lkrg/commit/d3118e45e66086190fa0a3a25eee93fd42e78bed works on Debian Bullseye Alpha 3 (testing), `5.9.0-5-amd64` kernel. Lockdown mode is deactivate due to the above-mentioned limitations.

**Comment by solardiz** [comment]
FWIW, regarding kprobes attack surface concerns raised here, from Adam's latest testing of LKRG 0.9.0:

```
I can confirm that LKRG works fine while:

CONFIG_KPROBES=y
CONFIG_KPROBE_EVENTS=n
CONFIG_UPROBES=n
CONFIG_UPROBE_EVENTS=n
CONFIG_FTRACE=n
CONFIG_EVENT_TRACING=n

There is no attack surface exposed to user-mode ;-)
```

**Comment by solardiz** [comment]
I think I need to add that setting `CONFIG_FTRACE=n` _probably_ increases LKRG's performance impact (_likely_ making it higher than e.g. what Phoronix reported), but we don't have such benchmarks yet.
