### ISSUE TITLE
Signed github source

### ISSUE THREAD

**Issue by morfikov** [openwall/lkrg#66]
LKRG source is signed, but the signature file is only available on its [website](https://www.openwall.com/lkrg/). Can you also include the signature file in the github releases page?

**Comment by solardiz** [comment]
https://github.com/openwall/lkrg/releases currently has tarballs auto-generated by GitHub based on git tags. That's not what our release signatures are valid for - they're for tar.gz files I created on the computer where I sign Openwall releases. We could switch to signing whatever tarballs GitHub generates, but that would unnecessarily put more trust into GitHub or/and require extra manual review before signing. Maybe the .tar files prior to compression are actually identical (now that with 0.9.0 we've started to use `git archive`) if they're from the same or similar versions of GNU tar, or maybe the same can even be achieved for .tar.gz, but even if so that would be fragile - not something we can rely on working for future releases.

Alternatively, we could remove the "Releases" section. GitHub has a checkbox that we can uncheck to do this.

Alternatively, we can probably reuse GitHub "Releases" for manually-uploaded release tarballs, overriding those generated by GitHub. This sounds like extra work for little gain, though, since we're happy hosting those release tarballs ourselves and will continue doing so anyway and they're also getting onto Openwall file archive mirrors (including kernel.org's).

Or we can leave everything as-is.

Any preferences? Any other suggestions?

**Comment by morfikov** [comment]
It depends, because when a user see here on github something in the Releases section, he can assume that is the source you've provided. If you have an external website to store the tar.gz files along with the signatures, I think there's only two ways to go. One is to remove the Release section here (and provide some info with the link to the actual releases), or as mentioned, override the auto generated tar.gz files and add signatures so everything was in one place (and also add the mirror info). If the second option is "too much work", I think it's better to remove the Releases section to avoid unecessary confusion.

**Comment by solardiz** [comment]
OK, I removed "Releases" for now. The same GitHub-generated tarballs can also be downloaded via the tags link anyway, but they're not "marketed" as releases now, so I guess wouldn't be expected to match our signatures.

GitHub also has a "Packages" feature, now disabled in this repo, which is another way/place for us to add externally generated files if we want to.

I'll close this issue for now, but if anyone has anything valuable to add they can post more comments to here. Thanks!
